apiVersion: argoproj.io/v1alpha1
kind: application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: cicd
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/pus1234567/argocd
    path: cicd-cluster/argocd
    targetReversion: dev
    helm:
      valuesFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
