apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app-of-apps
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    - path: root
      repoURL: https://github.com/pus1234567/argocd
      targetReversion: dev
    - path: cicd-cluster
      repoURL: https://github.com/pus1234567/argocd
      targetReversion: dev
